name: Disparar lembrete diário

on:
  schedule:
    - cron: '0 19 * * *' # Executa todos os dias às 19:00 PM 
  workflow_dispatch:
jobs:
  enviar-mensagem:
    runs-on: ubuntu-latest
    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v3

    - name: Configurar o Python no servidor
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        pip install twilio

    - name: Executar o script de envio
      env:
        # Vincula os segredos do GitHub com as variáveis do script
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      run: python lembrete.py